# Generated by Django 3.1.7 on 2021-06-03 14:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='You may keep it blank', max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('salary', models.PositiveIntegerField()),
                ('vacancy', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('job_category', models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Web Design and Development', 'Web Design & Development'), ('Data Science and Analytics', 'Data Science & Analytics'), ('Graphic Design', 'Graphic Design'), ('Software Quality Assurance', 'Software Quality Assurance'), ('Network and System Admin', 'Network & System Admin'), ('Information Technology', 'Information Technology'), ('Cloud Computing and Engineering', 'Cloud Computing & Engineering'), ('Cyber Security', 'Cyber Security')], max_length=50)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Remote', 'Remote'), ('Contractual', 'Contractual')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('company_website', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.TextField(max_length=200)),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur')], max_length=15)),
                ('description', models.TextField()),
                ('responsibility', models.TextField()),
                ('min_education', models.CharField(choices=[('Post Graduate', 'Post Graduate'), ('Graduate', 'Graduate'), ('HSC', 'HSC'), ('SSC', 'SSC')], max_length=20)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('experience', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('skill_req', models.TextField(help_text='Input skills with comma')),
                ('skill_bonus', models.CharField(blank=True, help_text='Input skills with comma', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Hidden', 'Hidden')], max_length=20)),
                ('publish', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('applicant', models.ManyToManyField(blank=True, related_name='jobs', to='account.Applicant')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='account.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('education_application', models.CharField(choices=[('Post Graduate', 'Post Graduate'), ('Graduate', 'Graduate'), ('HSC', 'HSC'), ('SSC', 'SSC')], max_length=20)),
                ('cgpa_application', models.DecimalField(decimal_places=2, max_digits=3)),
                ('skill_req_application', models.TextField()),
                ('skill_bonus_application', models.CharField(blank=True, max_length=255, null=True)),
                ('related_experience_application', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('total_experience_application', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('note_application', models.TextField(blank=True, null=True)),
                ('cv_application', models.FileField(upload_to='')),
                ('applicant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobApplications', to='account.applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cvrecommender.job')),
            ],
        ),
    ]
