# Generated by Django 3.1.7 on 2021-06-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrecommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
