# Generated by Django 3.1.7 on 2021-06-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210603_2111'),
        ('cvrecommender', '0002_jobapplication_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicant',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='account.Applicant'),
        ),
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='account.recruiter'),
        ),
    ]
