# Generated by Django 3.1.7 on 2021-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrecommender', '0005_auto_20210605_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
