# Generated by Django 3.1.7 on 2021-06-23 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvrecommender', '0007_auto_20210623_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='total_experience_application',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
